name: Tests
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: "go.mod"

      - name: Build vendor
        run: go mod vendor

      - name: Run tests
        run: go test -count 1 -v -timeout 10m ./...